"""Verify that raw primary records were generated by the released source tree."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Dict, Mapping, Sequence, Tuple


ROOT = Path(__file__).resolve().parents[1]


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _require_source_map(value: object, label: str) -> Dict[str, str]:
    if not isinstance(value, Mapping) or not value:
        raise ValueError(f"{label} has no source_sha256 map")
    result: Dict[str, str] = {}
    for raw_name, raw_digest in value.items():
        name = str(raw_name).replace("\\", "/")
        digest = str(raw_digest).lower()
        if len(digest) != 64 or any(character not in "0123456789abcdef" for character in digest):
            raise ValueError(f"{label} has an invalid digest for {name}")
        relative = Path(name)
        if relative.is_absolute() or ".." in relative.parts:
            raise ValueError(f"{label} has a non-repository source path: {name}")
        path = (ROOT / relative).resolve()
        try:
            path.relative_to(ROOT.resolve())
        except ValueError as error:
            raise ValueError(f"{label} source escapes the repository: {name}") from error
        if not path.is_file():
            raise ValueError(f"{label} source is missing: {name}")
        observed = _sha256(path)
        if observed != digest:
            raise ValueError(
                f"{label} source hash mismatch for {name}: "
                f"recorded={digest}, current={observed}"
            )
        result[name] = digest
    return result


def _load(path: Path) -> Mapping[str, object]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, Mapping):
        raise ValueError(f"{path} is not a JSON object")
    return value


def verify_family(
    label: str,
    records: Sequence[Tuple[Path, Sequence[str]]],
) -> Dict[str, str]:
    maps = []
    for path, keys in records:
        value: object = _load(path)
        for key in keys:
            if not isinstance(value, Mapping) or key not in value:
                raise ValueError(f"{path} is missing {'.'.join(keys)}")
            value = value[key]
        maps.append(_require_source_map(value, str(path.relative_to(ROOT))))
    if any(source_map != maps[0] for source_map in maps[1:]):
        raise ValueError(f"{label} records were generated by different source snapshots")
    return maps[0]


def verify_tomography_bindings(
    raw_paths: Sequence[Path], summary_path: Path
) -> None:
    """Bind the tomography summary, raw records, and frozen checkpoints."""

    summary = _load(summary_path)
    if (
        summary.get("format") != "response-tomography-summary-v2"
        or summary.get("status")
        != "validated_three_seed_structured_response_tomography"
    ):
        raise ValueError("response tomography summary has the wrong identity")
    raw_map = summary.get("raw_result_sha256")
    if not isinstance(raw_map, Mapping):
        raise ValueError("response tomography summary lacks raw-result hashes")
    expected_names = {
        path.relative_to(ROOT).as_posix() for path in raw_paths
    }
    normalized_raw_map = {
        str(name).replace("\\", "/"): str(digest).lower()
        for name, digest in raw_map.items()
    }
    if set(normalized_raw_map) != expected_names:
        raise ValueError("response tomography raw-result inventory is incomplete")

    for seed, path in enumerate(raw_paths):
        relative = path.relative_to(ROOT).as_posix()
        observed_raw = _sha256(path)
        if normalized_raw_map[relative] != observed_raw:
            raise ValueError(
                f"response tomography raw hash mismatch for {relative}"
            )
        payload = _load(path)
        checkpoint = payload.get("checkpoint")
        if not isinstance(checkpoint, Mapping):
            raise ValueError(f"{relative} lacks checkpoint provenance")
        language = checkpoint.get("language_config")
        if not isinstance(language, Mapping) or int(language.get("seed", -1)) != seed:
            raise ValueError(f"{relative} has the wrong training seed")
        checkpoint_path = (
            ROOT / "results" / "checkpoints" / f"language_seed{seed}.pt"
        )
        if str(checkpoint.get("sha256", "")).lower() != _sha256(checkpoint_path):
            raise ValueError(
                f"{relative} does not bind the released seed-{seed} checkpoint"
            )

    summarizer = ROOT / "experiments" / "summarize_response_tomography.py"
    if str(summary.get("summary_source_sha256", "")).lower() != _sha256(
        summarizer
    ):
        raise ValueError("response tomography summary-source hash mismatch")


def verify_release_sources() -> Dict[str, Dict[str, str]]:
    primary = ROOT / "results" / "primary_remote"
    results = ROOT / "results"
    response = [
        (primary / f"response_audit_seed{seed}.json", ("source_sha256",))
        for seed in range(3)
    ]
    router = [
        (
            primary / f"router_decisions_seed{seed}.json",
            ("checkpoint", "source_sha256"),
        )
        for seed in range(3)
    ]
    aslora = [
        (results / f"aslora_seed{seed}" / "audit.json", ("source_sha256",))
        for seed in range(3)
    ]
    aslora_provenance = [
        (
            results / f"aslora_seed{seed}" / "provenance.json",
            ("source_sha256",),
        )
        for seed in range(3)
    ]
    probes = [
        (results / "probes_mlp.json", ("generation", "source_sha256")),
        (
            results / "probes_transformer.json",
            ("generation", "source_sha256"),
        ),
    ]
    tomography_raw_paths = [
        results / f"response_tomography_seed{seed}.json"
        for seed in range(3)
    ]
    tomography_summary = results / "response_tomography_summary.json"
    tomography = [
        (path, ("source_sha256",)) for path in tomography_raw_paths
    ] + [(tomography_summary, ("source_sha256",))]
    verified = {
        "response": verify_family("response", response),
        "router_decision": verify_family("router decision", router),
        "aslora_audit": verify_family("ASLoRA audit", aslora),
        "aslora_provenance": verify_family(
            "ASLoRA provenance", aslora_provenance
        ),
        "probes": verify_family("paired functional probes", probes),
        "response_tomography": verify_family(
            "response tomography", tomography
        ),
    }
    if verified["aslora_audit"] != verified["aslora_provenance"]:
        raise ValueError("ASLoRA audit and provenance source maps differ")
    required_tomography_sources = {
        "experiments/run_response_tomography.py",
        "src/response_tomography.py",
        "src/response_identifiability.py",
        "src/language.py",
        "src/models.py",
    }
    if set(verified["response_tomography"]) != required_tomography_sources:
        raise ValueError("response tomography source inventory is incomplete")
    verify_tomography_bindings(tomography_raw_paths, tomography_summary)
    return verified


def main() -> None:
    verified = verify_release_sources()
    counts = ", ".join(
        f"{name}={len(source_map)}" for name, source_map in verified.items()
    )
    print(f"verified generation-time source hashes against release ({counts})")


if __name__ == "__main__":
    main()
